### ISSUE TITLE
cannot build visual studio project

### ISSUE THREAD

**Issue by ivandrodri** [floooh/oryol-samples#10]
Hello, I am trying to build a visual studio project of the oryol-samples but I have this error:

C:/Documents/3D-interface/oryol-samples/src/KC85-3/shaders.shd(70): error : 
C:/Documents/3D-interface/oryol-samples/src/KC85-3/test.vox is not a VOX file! [C:\Use
rs\ivand\Documents\3D-interface\3D-UI\fips-build\oryol-samples\win64-vs2015-debug\oryol_Dbg\ALL_GENERATE.vcxproj]

Thanks in advance for any help!

**Comment by floooh** [comment]
Hi, I cannot reproduce this on a fresh checkout. The error happens in a python code-generator script when the "test.vox" voxel data file has a broken magic number:

https://github.com/floooh/oryol-samples/blob/7f01ccdd9853a18aef0a405a1bb634fa954314ba/fips-generators/ImportVox.py#L76-L77

My guess is that the file ```oryol-samples/src/KC85-3/test.vox``` has been corrupted somehow, the MD5 checksum should be:

```
019e154887b86962dd627f6698f415ce
```
On Windows you can get the MD5 checksum like this:
```
> cd oryol-samples/src/KC85-3
> CertUtil -hashfile test.vox MD5
```
If the checksum doesn't match, I would try a fresh checkout. If the checksum *does* match, please let me know, as this would point to another reason for the problem.

**Comment by floooh** [comment]
PS: what's your python version? Maybe it's one of those subtle python2 vs python3 differences (I have tested on Win7 with Python 2.7.12)?

**Comment by ivandrodri** [comment]
Hi, thanks a lot for the quick reply. I used both versions python2 and python3 but the error is the same and it only happens in Windows. With Linux everything if fine. I'll check tomorrow the MD5 checksum in my Windows pc and I let you know!

**Comment by ghost** [comment]
I have the exact same error with VC 19. The hash is identical. 
![image](https://user-images.githubusercontent.com/18743986/92608886-8fe3cb00-f2be-11ea-9f10-71d161894885.png)


```
 tb_core.cpp
  soloud_dcremovalfilter.cpp
  tb_debug.cpp
  soloud_echofilter.cpp
  Logger.cc
  btSimpleBroadphase.cpp
  win32_init.c
  OmshParser.cc
  soloud_fftfilter.cpp
  ## shader code gen: F:/Dropbox/Tech/production/ppc/OR/oryol/code/Modules/Dbg/private/DebugShaders.glsl
  ## shader code gen: F:/Dropbox/Tech/production/ppc/OR/oryol-imgui/src/IMUI/IMUIShaders.shd
  ## shader code gen: F:/Dropbox/Tech/production/ppc/OR/oryol-nuklear/src/NKUI/NKUIShaders.shd
  ## shader code gen: F:/Dropbox/Tech/production/ppc/OR/oryol-tbui/src/TBUI/tb/TBUIShaders.shd
  ## shader code gen: F:/Dropbox/Tech/production/ppc/OR/oryol-samples/src/Common/wireframe_shaders.glsl
  ## shader code gen: F:/Dropbox/Tech/production/ppc/OR/oryol-samples/src/KC85-3/shaders.shd
  load_ams.cpp
F:/Dropbox/Tech/production/ppc/OR/oryol-samples/src/KC85-3/shaders.shd(97): error : F:/Dropbox/Tech/production/ppc/OR/oryol-samples/src/KC85-3/test.vox is not a VOX file! [F:\Dropbox\Tech\production\ppc\OR\fips-build\oryol-samples\win64-vstudio-release\oryol_Dbg\ALL_GENERATE.vcxproj]
  F:/Dropbox/Tech/production/ppc/OR/fips-build/oryol-samples/win64-vstudio-release/fips-gen.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  soloud_flangerfilter.cpp
  tb_dimension.cpp
  RunLoop.cc
  tb_editfield.cpp
```

**Comment by floooh** [comment]
yeah it seems this is a python2 vs python3 problem, I guess back in 2017 when I wrote that I cannot reproduce this I tested with python2 (on the other hand, python2 also didn't work, however this same error now also happens on my Windows10 PC)
