### ISSUE TITLE
‘kc85_exp’ was not declared

### ISSUE THREAD

**Issue by tni711** [floooh/oryol-samples#14]
Hi, 

Thank you for sharing this wonderful samples project. The sample projects here are very impressive. I really like to learn how everything works here.

It seems like the KC85Emu.cc module is out of sync with the YAKC module. I got the following build errors when I build the oryol-samples from the git master. After I commented out the the EmuCommon and KC85-3 from the CMakeLists.txt, everything else works!

** compilation error **
fips-workspace/oryol-samples/src/EmuCommon/KC85Emu.cc: In member function ‘void Oryol::KC85Emu::Setup(const Oryol::GfxSetup&, YAKC::system, YAKC::os_rom)’:
/home/tangth/fips-workspace/oryol-samples/src/EmuCommon/KC85Emu.cc:41:9: error: ‘kc85_exp’ was not declared in this scope
         kc85_exp.register_none_module("NO MODULE", "Click to insert module!");
         ^~~~~~~~

**Comment by floooh** [comment]
Yes sorry about that, I rewrote big parts of the YAKC emulator recently, and haven't fixed the Oryol samples yet. I have temporarily removed the emulator sample in d968415d07c06ef6c4493d8e51ef27c6b22aeceb, when you do an update on the oryol-samples project and run "./fips gen" again, everything should build.
