### ISSUE TITLE
Wrong path of demo resources

### ISSUE THREAD

**Issue by RobertoMalatesta** [floooh/oryol-samples#5]
Hi, @floooh, 
just  git-cloned the samples and saw that after the build on my Linux some demos (those who need resources) do run but have missing models and resources i.e.:

**./fips run MeshViewer**
does not show the models (I suppose it's going to look for them in a wrong place)
&
**./fips run TurboBadgerDemo**
emits a long list of loadQueue errors:
`loadQueue:: failed to load file 'http://floooh.github.com/oryol/data/tbui/default_skin/search.png' with 'NotFound'
loadQueue:: failed to load file 'http://floooh.github.com/oryol/data/tbui/default_skin/checkbox_pressed.png' with 'NotFound'
`
hth,

--R

**Comment by floooh** [comment]
Yep, known issue :) I forgot to fix the path after copying the samples over to the new git repo. Looking into it...

**Comment by floooh** [comment]
Alright, this should be fixed in commit 155ea888c330fbf680108c43809891fc38e178da, just run

```
> ./fips clean
> ./fips gen
```

So that the build files pick up the new URL.

**Comment by RobertoMalatesta** [comment]
./fips run SoloudMOD
still has some problems
`
App::onFrame(): Switching to app state 'Running'
curlURLLoader: curl_easy_peform failed with 'http://localhost:8000/disco_feva_baby.s3m.txt' for 'Failed to connect to localhost port 8000: Connection refused', httpStatus='0'
curlURLLoader: curl_easy_peform failed with 'http://localhost:8000/jungle_juice.mod.txt' for 'Failed to connect to localhost port 8000: Connection refused', httpStatus='0'
curlURLLoader: curl_easy_peform failed with 'http://localhost:8000/porn_industryy.xm.txt' for 'Failed to connect to localhost port 8000: Connection refused', httpStatus='0'
curlURLLoader: curl_easy_peform failed with 'http://localhost:8000/comsi.s3m.txt' for 'Failed to connect to localhost port 8000: Connection refused', httpStatus='0'
curlURLLoader: curl_easy_peform failed with 'http://localhost:8000/dgtinnv1.mod.txt' for 'Failed to connect to localhost port 8000: Connection refused', httpStatus='0'
curlURLLoader: curl_easy_peform failed with 'http://localhost:8000/bruce.s3m.txt' for 'Failed to connect to localhost port 8000: Connection refused', httpStatus='0'
curlURLLoader: curl_easy_peform failed with 'http://localhost:8000/sunshine.xm.txt' for 'Failed to connect to localhost port 8000: Connection refused', httpStatus='0'
`
as well as other sound demos:
./fips run SoloudTedSid
`App::onFrame(): Switching to app state 'Running'
curlURLLoader: curl_easy_peform failed with 'http://localhost:8000/modulation.sid.dump' for 'Failed to connect to localhost port 8000: Connection refused', httpStatus='0'
curlURLLoader: curl_easy_peform failed with 'http://localhost:8000/ted_storm.prg.dump' for 'Failed to connect to localhost port 8000: Connection refused', httpStatus='0'
loadQueue:: failed to load file 'http://localhost:8000/ted_storm.prg.dump' with 'InvalidIOStatus'
loadQueue:: failed to load file 'http://localhost:8000/modulation.sid.dump' with 'InvalidIOStatus'
`

just to be of help :)

--R

**Comment by floooh** [comment]
Ah ok, those sound demos go to a different URL based on whether debug mode is on or off. I'll fix that in the evening.

In the meantime, 2 workarounds should work:

``` bash
# run a local HTTP server under oryol-samples/files before running the sound samples
> cd oryol-samples/files
> python -m SimpleHTTPServer
```

Or, compile in release mode:

``` bash
> ./fips set config linux-make-release
> ./fips build
> ./fips run SoloudMOD
...
```

Your bug reports are much appreciated btw :)

**Comment by floooh** [comment]
Ok, now it should work the same across all samples. Please don't hesitate to report more things that don't work or or look confusing :)

Thanks!

**Comment by RobertoMalatesta** [comment]
**cd data** instead of **files** does the trick.

**./fips run SoundTest** still seems to have problems tho,
with no significant resource error message, even in **linux-make-release**.

I'm peeking in to **Oryol** every three months and the progress I see is **impressive**.
Sorry not to have more time to collaborate more effectively.

--R
